name: Multi job pipeline
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build step
      runs: echo "Build Application"

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test step
      runs: echo "Testing application"

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy step
      runs: echo "Deploy application"
