name: Real CI step
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: show files
      run: ls -la

    - name: Read File
      run: cat first.txt

    - name: Create temp file
      run: echo "Created from inside the pipeline" > output.txt

    - name: show files after creation
      run: ls -la

    - name: Read generated output
      run: cat output.txt

    - name: Current working directory
      run: pwd

    - name: Who am I
      run: whoami
