name: Env Pipeline
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PASSWORD: 123456789
      APP_NAME: DevopsApp
      ENVIRONMENT: staging

    steps:
    - name: Password Printing
      run: echo "Password: $PASSWORD"

    - name: Print app name
      run: echo "App is $APP_NAME"

    - name: Print environment
      run: echo "Deploying to $ENVIRONMENT"
